dist: trusty
language: python
sudo: false
cache: pip
python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - pip install -e ".[test]"

script:
  - pytest src --doctest-modules
